
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;



public class Registration extends javax.swing.JFrame {

    static void setvalue(String stuid, String mbl, String amount, String accounttyp, String dat) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    String fn, add;
    String mbl;
    String mail;
    String ids;
    String pass;
    String dat;
    JFileChooser fc;
    File drt;
    DefaultTableModel model;
    File file = null;

    static Connection connect;
    static PreparedStatement pres;

    public static void setvalue(String name, String phone, String mail, String pass, String date, String id, String add) throws SQLException {

        String query = "INSERT INTO student (id, name, phone, mail, password,date,student_id, address) VALUES (NULL, ?, ?, ?, ?, ?, ?, ?)";
        pres = (PreparedStatement) connect.prepareStatement(query);

        pres.setString(1, name);
        pres.setString(2, phone);
        pres.setString(3, mail);
        pres.setString(4, pass);
        pres.setString(5, date);
        pres.setString(6, id);
        pres.setString(7, add);
        pres.execute();

        pres.close();
        connect.close();
    }

    /**
     * Creates new form Guitar
     */
    public Registration() {
        initComponents();
        model = new DefaultTableModel();
        tblstudent.setModel(model);
        model.addColumn("Name");
        model.addColumn("Mobile");
        model.addColumn("Email");
        model.addColumn("Password"); //not fill please add
        model.addColumn("Date");      //not fil please add
        model.addColumn("Student Id");
        model.addColumn("Address");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtnamer = new javax.swing.JTextField();
        txtmob = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        dateval = new com.toedter.calendar.JDateChooser();
        idvalue = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtadd = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblstudent = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btndsub = new javax.swing.JButton();
        btndply = new javax.swing.JButton();
        btnbk = new javax.swing.JButton();
        btnclr = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("STUDENT REGISTRATION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/guitar icon.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/guitar icon.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 580, -1));

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mobile");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 67, 83, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 117, 53, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Name");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 11, 51, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 172, 82, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 224, 45, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Student Id");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 269, 82, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 401, 580, -1));
        jPanel2.add(txtnamer, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 11, 250, -1));
        jPanel2.add(txtmob, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 67, 250, -1));
        jPanel2.add(txtmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 117, 250, -1));
        jPanel2.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 172, 250, -1));

        dateval.setDateFormatString("dd-MM-yyyy");
        jPanel2.add(dateval, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 221, 250, -1));
        jPanel2.add(idvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 269, 250, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Address");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 307, 82, -1));
        jPanel2.add(txtadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 307, 250, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Student Infoemation :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 356, 143, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 580, 410));

        tblstudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Mobile", "Email", "Password", "Date", "Student Id", "Address"
            }
        ));
        jScrollPane1.setViewportView(tblstudent);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 580, 100));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        btndsub.setBackground(new java.awt.Color(0, 204, 255));
        btndsub.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btndsub.setText("SUBMIT");
        btndsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndsubActionPerformed(evt);
            }
        });

        btndply.setBackground(new java.awt.Color(0, 204, 255));
        btndply.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btndply.setText("DISPLAY");
        btndply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndplyActionPerformed(evt);
            }
        });

        btnbk.setBackground(new java.awt.Color(0, 204, 255));
        btnbk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnbk.setText("BACK");
        btnbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbkActionPerformed(evt);
            }
        });

        btnclr.setBackground(new java.awt.Color(0, 204, 255));
        btnclr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnclr.setText("CLEAR");
        btnclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndsub)
                .addGap(39, 39, 39)
                .addComponent(btndply)
                .addGap(48, 48, 48)
                .addComponent(btnclr, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnbk, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndsub)
                    .addComponent(btndply)
                    .addComponent(btnbk)
                    .addComponent(btnclr))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 610, 580, 60));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/guitar home.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 820));

        setSize(new java.awt.Dimension(1465, 829));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btndsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndsubActionPerformed
        //save
        
        fn = txtnamer.getText().trim();
        mbl = txtmob.getText();
        mail = txtmail.getText();
        pass = txtpass.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

        dat = sdf.format(dateval.getDate());
        ids = idvalue.getText();
        add = txtadd.getText();

        connect = databaseConnection.connection();

        try {
            Registration.setvalue(fn, mbl, mail, pass, dat, ids, add);
        } catch (SQLException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        getAllRecord();
        if (txtnamer.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please Enter your Name.");
            txtnamer.requestFocus();
            //behind else will be close(mobile to student id)
        } else {
            if (txtmob.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Please Give your Mobile Number.");
                txtmob.requestFocus();

            } else {

                if (txtmail.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(rootPane, "Please Give your Email.");
                    txtmail.requestFocus();
                } else {
                    if (txtpass.getName().isEmpty()) {
                        JOptionPane.showMessageDialog(rootPane, "Please Give your Password.");
                        txtpass.requestFocus();
                    } else {
                        if (dateval.getName().isEmpty()) {
                            JOptionPane.showMessageDialog(rootPane, "Please fill in Date.");
                            dateval.requestFocus();
                        } else {
                            if (idvalue.getText().isEmpty()) {
                                JOptionPane.showMessageDialog(rootPane, "Please Give Student's Id no.");
                                idvalue.requestFocus();
                                //behind else the block area form mob ile number
                            } else {
                                //after i coppied
                                if (txtadd.getText().isEmpty()) {
                                    JOptionPane.showMessageDialog(rootPane, "Please Give your Address.");
                                    txtadd.requestFocus();

                                } else {
                                    fc = new JFileChooser(drt);
                                    //add file filter
                                    FileNameExtensionFilter filter;
                                    filter = new FileNameExtensionFilter("*.txt", new String[]{"txt"});
                                    fc.addChoosableFileFilter(filter);
                                    int option = fc.showSaveDialog(this);
                                    if (option == JFileChooser.APPROVE_OPTION) {
                                        drt = fc.getCurrentDirectory();
                                        model.addRow(new Object[]{fn, mbl, mail, ids, pass, dat, add});

                                        file = fc.getSelectedFile();
                                        try {
                                            writeAll();
                                        } catch (IOException ex) {
                                            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
                                        }
                                    }
                                }

                            }

                        }
                    }
                }
            }

        }
       

        clear();

    }//GEN-LAST:event_btndsubActionPerformed

    private void btndplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndplyActionPerformed
        // TODO add your handling code here:
        displaytable();
    }//GEN-LAST:event_btndplyActionPerformed

    private void btnclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclrActionPerformed
        //clear
        clear();
    }//GEN-LAST:event_btnclrActionPerformed

    private void btnbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbkActionPerformed
        // TODO add your handling code here:
        dispose();
        AdminPortal object = new AdminPortal();
        object.show();
    }//GEN-LAST:event_btnbkActionPerformed
    private void getAllRecord() {
        fn = txtnamer.getText();

        //mobile to id
        //mobile 
        mbl = txtmob.getText();
        int length = mbl.length();

        if (length < 12) {
            txtmob.setEditable(true);
        } else {
            //not editable if the length is more then 11
            txtmob.setEditable(false);
        }

        pass = txtpass.getText();
        mail = txtmail.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        dat = sdf.format(dateval.getDate());
        ids = idvalue.getText();
        add = txtadd.getText();
    }

    private void writeAll() throws IOException {
        BufferedWriter buf = null;
        try {
            buf = new BufferedWriter(new FileWriter(file + getExtention(), true));
//blocked mobile to ids
            buf.write(fn + "," + mbl + "," + mail + "," + ids + "," 
                    + pass + "," + dat + "," + add);
            buf.newLine();
            JOptionPane.showMessageDialog(rootPane, "Data Saved");

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (buf != null) {
                buf.close();
            }
        }
    }

    private String getExtention() {
        String ext = "";
        String extension = fc.getFileFilter().getDescription();
        if (extension.equals("*.txt")) {
            ext = ".txt";

        }
        return ext;
    }

    private void displaytable() {
        InputStream is = null;
        fc = new JFileChooser(drt);
        int option = fc.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            file = fc.getSelectedFile();
            drt = fc.getCurrentDirectory();
            try {
                File f = file;
                is = new FileInputStream(f);
                Scanner scan = new Scanner(is);
                String[] arr;
                while (scan.hasNextLine()) {
                    String line = scan.nextLine();
                    if (line.indexOf(",") > 1) {
                        arr = line.split(",");
                    } else {
                        arr = line.split("\n");
                    }
                    Object[] data = new Object[arr.length];
                    for (int i = 0; i < data.length; i++) {
                        data[i] = arr[i];
                    }
                    model.addRow(data);
                }
            } catch (Exception e) {
                e.printStackTrace();
            } finally {

                try {
                    if (is != null) {
                        is.close();
                    }
                } catch (Exception e) {
                }
            }
        }

    }

    private void clear() {
        txtnamer.setText("");
        txtadd.setText("");
        //mobile to id   
        txtmob.setText("");
        txtpass.setText("");
        txtmail.setText("");
        dateval.setName("");
        idvalue.setText("");

        if (tblstudent.getRowCount() > 0) {
            for (int i = tblstudent.getRowCount() - 1; i > -1; i--) {
                model.removeRow(i);

            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbk;
    private javax.swing.JButton btnclr;
    private javax.swing.JButton btndply;
    private javax.swing.JButton btndsub;
    private com.toedter.calendar.JDateChooser dateval;
    private javax.swing.JTextField idvalue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblstudent;
    private javax.swing.JTextField txtadd;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtmob;
    private javax.swing.JTextField txtnamer;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
}
